### ISSUE TITLE
Http repeater improvement proposal: aggregated response summary on GUI

### ISSUE THREAD

**Issue by marcob79** [alexandrehtrb/Pororoca#113]
I have an improvement proposal for Pororoca GUI regarding HTTP requests function.
Supposing to send, 5000 requests, on top of the current information you can get from GUI or by downloading data, it would be nice to understand if all my requests were successful or....
I was thinking something like
2xx response: 4995
3xx response: 0
4xx response: 2
5xx response: 3

**Comment by alexandrehtrb** [comment]
Hello,

After running the repeater, you can click on `Export report...` and get a CSV file, that can be opened on Excel or in a text editor for counting ([excel example](https://www.exceldemy.com/excel-count-cells-with-specific-value/))
Or are you looking for showing in the GUI? Like showing: `Results - 97% successful`

**Comment by marcob79** [comment]
Hi,
yes, I know the export report function and it is nice.
However IMHO, it would be nice to have the possibility to have an execution summary directly on the GUI when the repeater execution ends.
Even raw number(s), not necessarily percentage
in order to have immediately the feeling if everything was good, or something need to be checked

**Comment by alexandrehtrb** [comment]
@marcob79 , what do you think?

![image](https://github.com/alexandrehtrb/Pororoca/assets/27026741/2f069029-a523-4cb5-8631-1aca9bdb9266)

**Comment by marcob79** [comment]
Nice idea

**Comment by alexandrehtrb** [comment]
Solved with release 3.4.2
