### ISSUE TITLE
Light theme proposal

### ISSUE THREAD

**Issue by lilacse** [alexandrehtrb/Pororoca#120]
I always found that Pororoca's light theme felt more like a "gray" theme instead. So, taking inspiration from other tools (mainly Insomnia), I put together some colours that resulted in a theme that looks like this:

![image](https://github.com/user-attachments/assets/d1044193-d50e-4ae9-84eb-0f585a325dce)
![image](https://github.com/user-attachments/assets/1381f8d2-a9c6-44ca-a715-0f83375dbea0)
![image](https://github.com/user-attachments/assets/80c6b4ac-4399-47f6-abd4-d316e10bc150)
![image](https://github.com/user-attachments/assets/410c368f-bfc0-485f-8c89-87d2c81a444c)

I'm hoping to contribute this theme to the project, but I'm not sure what to call it as, since personally I treated it as the "light theme", but we currently already have a theme called Light. 

Apart from the name, I'm also open to suggestions to the theme before I commit and try to PR it :) 

Thanks!

**Comment by alexandrehtrb** [comment]
Hello!

Your theme looks good!
We can add it as a new "Light 2" theme.
Feel free to open a PR!
