### ISSUE TITLE
lost all saved collections

### ISSUE THREAD

**Issue by marcob79** [alexandrehtrb/Pororoca#130]
Hi,
I upgraded recently to 3.7.0
This morning, when I opened to app, all my collections are gone.
Where are they stored by default?
is there any place I can have a look to check if there is the chance to recover them?

thanks
bye
Marco

**Comment by alexandrehtrb** [comment]
Hello Marco,

Probably there is no way to recover them. I'm sorry.
I removed the 3.7.0 release and I will make a fix as soon as possible.

The saving location is:

| Operating system | Packaging | `PororocaUserData` folder location |
|------------------|-----------|-----------------------------|
| Linux, Windows | portable | alongside the executable |
| Debian | deb | `/home/you/.config/Pororoca/` |
| Windows | installer | `C:\Users\you\AppData\Roaming\Pororoca\` |
| Mac OSX | application | `/Users/you/Library/Application Support/Pororoca/` |

**Comment by alexandrehtrb** [comment]
@marcob79 Which operating system do you use?

**Comment by marcob79** [comment]
Windows 10

**Comment by alexandrehtrb** [comment]
@marcob79 , a new release with a hotfix has been published. Collection files won't be deleted anymore, they will simply be renamed with a `deleted_` prefix.

However, I couldn't reproduce this bug and I can not identify the cause.

The only thing that comes to mind is that your Windows user account changed, so the user data folder path changed too. Was that it?

If there are other people with this same issue, please comment below (include the operating system and packaging you use, like portable or installed).

**Comment by marcob79** [comment]
I don't think user data folder path changed is the case. 
Moreover I'm quite sure i opened once after upgrade and everything was there....
I cannot explain with any action

**Comment by TWaalenApollo** [comment]
I also had this issue, all but one of my collections was deleted. I had not yet updated to 3.7.0.1, and I'm quite sure I launched 3.7.0 several times without issues. Currently trying to undelete them, but I'm sadly expecting them to be permanently gone.

I'm also on Windows 10 and don't think the user data folder path has changed as I did not rename my account or switch to a different account.

**Comment by alexandrehtrb** [comment]
I changed the code to avoid the race condition between load and save collections, which is probably the reason for this bug.

This update has been made and is available in the 3.7.0 release (I simply replaced the executables, no new release).

**Comment by flinthamm** [comment]
I've downloaded the latest windows x64 portable release 3.7.0 as of today 09/01/2025 and immediately it loads only one of the numerous collections is loaded. On exiting the software all (except the loaded collection) are renamed with the prefix deleted_ and when the software is run again nothing has changed and only the one collection is loaded. Fortunately the files still seem to be in tact but with the deleted_ prefix, so hopefully a future update will fix this :) 

For now a roll back looks like the only solution.

**Comment by alexandrehtrb** [comment]
Hello @flinthamm ,

Would you be willing to send me an email with your collections? This would help to diagnose the problem. (just make sure there are no secrets and confidential stuff)

I will understand if you can't.
