### ISSUE TITLE
Mac OS X version crashes on start

### ISSUE THREAD

**Issue by alancookie** [alexandrehtrb/Pororoca#18]
Using Pororoca_2.0.1_osx-x64 version on Mac OS X 10.12.6 "Sierra".  Do not see a minimum OS requirement for Mac?  Crashes when trying to launch app.  Please advise.

**Comment by alexandrehtrb** [comment]
Hello,

Pororoca uses Avalonia for its GUI and Avalonia support for Mac OSX requires version Mac OSX High Sierra 10.13 or higher ([link](https://docs.avaloniaui.net/#supported-platforms)).
