### ISSUE TITLE
Content-Types application/dns-json and application/dns-message are missing

### ISSUE THREAD

**Issue by SamLowryMOI** [alexandrehtrb/Pororoca#19]
I want to test DoH, would you please add Content-Types application/dns-json and application/dns-message? Thank you. Otherwise a very nice program!

-edit-
I was wrong. File as body type doesn't work, even with the right Content-Type. I need binary type with possibility to specify a file like in postman. That's probably a bit more complicated I think. What are the chances of something like this happening in the near future?

**Comment by alexandrehtrb** [comment]
Hello @SamLowryMOI ,

Do you want these Content-Types available as text in responses, or available in requests? (or both?)
The MIME type for unspecified binary content is `application/octet-stream`
Is this what you would like?

![image](https://user-images.githubusercontent.com/27026741/232372769-92336ed9-c9fb-4d89-97bd-3ed423f15084.png)

**Comment by SamLowryMOI** [comment]
> Do you want these Content-Types available as text in responses, or available in requests? (or both?)

Neither nor.

I was wrong. File as body type doesn't work, even with the right Content-Type. I need 'binary' as body type with possibility to specify a file like in postman. That's probably a bit more complicated I think. What are the chances of something like this happening in the near future?

**Comment by alexandrehtrb** [comment]
Is this the error you are receiving?

![image](https://user-images.githubusercontent.com/27026741/232645220-111b0a54-1828-4953-a66e-c5293c43a34e.png)

To fix this, I will add `application/dns-json` and `application/dns-message` MIME types in the next release.

The "binary" body type in Postman is actually `Content-Type: application/octet-stream`, which is available in Pororoca.

**Comment by SamLowryMOI** [comment]
I didn't realize that the 'binary' in Postman is called 'File' in Pororoca, my fault. I just added the two entries to the BuildMappings list and everything works as expected. So if you add this to the next release, it will be possible to do DoH queries with Pororoca. Thanks a lot!

**Comment by alexandrehtrb** [comment]
Fixed on release 2.1.0!
