### ISSUE TITLE
Show WebSocket connection response status code and headers

### ISSUE THREAD

**Issue by alexandrehtrb** [alexandrehtrb/Pororoca#36]
Starting at .NET 7, ClientWebSocket can show the connection response status code and headers. This would be a useful information for users and could be presented on the WebSocket connection screen, probably in the middle section, in a Connection response tab.

Should not be hard.

Files to be edited: WebSocketConnectionView.xaml, WebSocketConnectionViewModel.cs, PororocaWebSocketConnector.cs

**Comment by pipliya** [comment]
@naitii Please check this requirement.

**Comment by tetropolix** [comment]
Hi, I would like to help with this issue (if it is still available) - how should I proceed? Just create my own fork and then create a PR or should I firstly be assigned to this issue. Thanks

**Comment by alexandrehtrb** [comment]
Hi,

This issue is available, I can assign it to you if you want!

Yes, fork the repo starting from the develop branch, then open a PR to our repo's develop branch

**Comment by tetropolix** [comment]
Thanks, if it is possible to became an asignee then I would like to try it as my first issue.

**Comment by tetropolix** [comment]
I have created a PR; I'm not sure if I did it correctly, but I would be glad to hear any form of feedback. Thanks

**Comment by alexandrehtrb** [comment]
@tetropolix , what is your opinion?

Connection failed:

![Captura de tela de 2023-11-12 15-47-45](https://github.com/alexandrehtrb/Pororoca/assets/27026741/b3a7bd1c-4922-4666-b5ae-5dd14dae9bdf)

Connection success:

![Captura de tela de 2023-11-12 15-45-50](https://github.com/alexandrehtrb/Pororoca/assets/27026741/53114e60-5d1d-4e69-978f-06c0bfec98a3)

**Comment by tetropolix** [comment]
Well, if you are asking me if it is readable and intuitive from the perspective of "junior developer" I would say yes. On the other hand I cannot confidently state if it includes all the necessary information for inspection as I do not know all of the inner workings of websocket over http2.

**Comment by alexandrehtrb** [comment]
Yes, I was asking about the layout. If it is OK, then I will proceed with this design.

WebSocket over HTTP/2 is pretty much the same as WebSocket over HTTP/1.1, the difference is only at the transport level

I will include this in the next release

**Comment by alexandrehtrb** [comment]
Solved with release 2.5.0
