### ISSUE TITLE
Iterate through List of Values

### ISSUE THREAD

**Issue by phonique** [alexandrehtrb/Pororoca#40]
Hey Alex,

Accidentally found Pororoca and was wondering, if it'd be a big effort (and if you'd find it useful) to add a feature to automatically iterate through a list/array e.g. if you have somedomain.foo/{{User}}/someaction and {{User}} is a list of values, to perform an individual request with each of them and save the responses.

Thanks!

**Comment by alexandrehtrb** [comment]
Hello @phonique ,

This is a great idea. It could be used in many scenarios, like load testing and multiple requests at the same time.

JMeter, for example, allows this kind of multiple parameterized requests by taking values from a CSV input file, and these values can be used in the URL, body and headers. Do you think something similar would fit as a solution?

**Comment by phonique** [comment]
Great, that you like the idea, @alexandrehtrb !

A CSV similar to JMeter would certainly work well, as it would then also be possible to have the list generated (externally).
Including a rudimentary way to create a list in the UI would still be very useful for smaller numbers of values.

Admittedly, I haven't looked how the current collections are saved and whether it would break interoperability with postman if you include files (inline?) in there, but if that's possible, a "file" per variable would probably be a straightforward convention to follow.

**Comment by alexandrehtrb** [comment]
Solved in release 3.1.0!
