### ISSUE TITLE
Support Windows Authentication (Negotiate)

### ISSUE THREAD

**Issue by OronDF343** [alexandrehtrb/Pororoca#49]
Pororoca does not currently support Windows Authentication at all, so it cannot be used to test many of our intranet apps.

Please add support for enabling Windows Authentication, at the very least on Windows platforms please allow using the default credentials of the current user (`CredentialCache.DefaultNetworkCredentials`).

**Comment by alexandrehtrb** [comment]
Windows Authentication is not hard to implement in the client-side, but I could not find a good example server for ASP.NET Core, to test if it would work end-to-end.

Would you be willing to test this feature?

**Comment by OronDF343** [comment]
I could do some basic tests against two internal services, one Kestrel and one IIS (starting the week after next)

On October 4, 2023 4:05:23 AM GMT+03:00, "Alexandre H.T.R. Bonfitto" ***@***.***> wrote:
>Windows Authentication is not hard to implement in the client-side, but I could not find a good example server for ASP.NET Core, to test if it would work end-to-end.
>
>Would you be willing to test this feature?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alexandrehtrb/Pororoca/issues/49#issuecomment-1745972111
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alexandrehtrb** [comment]
@OronDF343 , Windows Authentication is available for testing in develop branch

You can either test using `dotnet run` locally or produce a release using the makereleases.ps1 script

If you choose the script, edit lines 56 and 57 to choose `win-x64_portable` and make sure to use a Windows machine with .NET SDK 7.0.306 installed (the version specified in global.json)

**Comment by OronDF343** [comment]
@alexandrehtrb Tested, looks good to me

**Comment by alexandrehtrb** [comment]
Solved with release 2.4.0
