### ISSUE TITLE
Re-run response captures reusing the current response

### ISSUE THREAD

**Issue by alexandrehtrb** [alexandrehtrb/Pororoca#52]
We can add a button to re-run response captures, such that users don't need to send a request again to capture the variables.

**Comment by Nishith-Savla** [comment]
Can you please explain this in a bit more detail? I would like to contribute to it.

**Comment by alexandrehtrb** [comment]
> Can you please explain this in a bit more detail? I would like to contribute to it.

Imagine a button like the yellow drawing in the picture below.
When the user clicks on it, the response captures would be executed again, without sending a new request, but reusing the same response, if already exists one.
This is useful in case the user made a mistake defining the capture. For example, in the picture, the user wanted to capture "title", but instead typed "author":

![image](https://github.com/alexandrehtrb/Pororoca/assets/27026741/d345c720-998c-4ee9-aabf-533373f988b5)

**Comment by alexandrehtrb** [comment]
@Nishith-Savla , would you like to be assigned for this issue?

**Comment by Nishith-Savla** [comment]
Give me some time. I am busy with something else currently.

**Comment by alexandrehtrb** [comment]
Solved, will be included in the next release
