### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by Karthikdasari0423** [alexandrehtrb/Pororoca#6]
hai ,

It is not an issue.
one small quick query

@alexandrehtrb 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by alexandrehtrb** [comment]
Hello @Karthikdasari0423 ,

As we spoke, the maintainers of AIOQUIC can better help you, as I do not have experience with it...

Good luck!

**Comment by Karthikdasari0423** [comment]
Hai @alexandrehtrb 

Thank you for replying back and

i don't think we spoke earlier on this issue or any of the issue.


Thank you
@Karthikdasari0423

**Comment by Karthikdasari0423** [comment]
Hai @alexandrehtrb

Thank you for replying back and

i don't think we spoke earlier on this issue or any of the issue.

Thank you
@Karthikdasari0423

**Comment by Karthikdasari0423** [comment]
Hai @alexandrehtrb

Thank you for replying back and

i don't think we spoke earlier on this issue or any of the issue.

anyway there were multiple issues created by others in the aioquic
repository regarding this issue.(
https://github.com/aiortc/aioquic/issues?q=is%3Aissue+is%3Aopen+streams).

Thank you
@Karthikdasari0423
