### ISSUE TITLE
Deb not registered by Gnome

### ISSUE THREAD

**Issue by faveoled** [alexandrehtrb/Pororoca#74]
After installing Pororoca it didn't appear in the list of apps:
![image](https://github.com/alexandrehtrb/Pororoca/assets/85760289/92453baf-ea86-48b7-ba2a-ef780a147236)

**Comment by alexandrehtrb** [comment]
Hey,

Thanks for reporting this issue, I will take a look.

In the meanwhile, you can use the `linux-x64` version.

**Comment by alexandrehtrb** [comment]
How did you install the package? Was it:

```bash
sudo apt install Pororoca_version_amd64.deb
```

Please try installing with the alternatives below:

```bash
sudo dpkg -i Pororoca_version_amd64.deb
```

or

```bash
sudo apt-get install ./Pororoca_version_amd64.deb
```

**Comment by faveoled** [comment]
Tried all ways, same bad result.
I suggest you do the following: make pororoca a script in /usr/bin and simplify your desktop file with just `pororoca` call:
```
Exec=LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/pororoca pororoca
```
I think Gnome can't parse this exec line and skips the app altogether

**Comment by faveoled** [comment]
Alternatively you can use this line (tested and works with Gnome):
```
Exec=env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/pororoca pororoca
```

**Comment by alexandrehtrb** [comment]
Solved

The `.deb`package for release 3.0.1 has been updated and fixes this issue

I used your suggestion of the script, thanks for the tip!
