### ISSUE TITLE
Better error reporting on capture without environment

### ISSUE THREAD

**Issue by telenieko** [alexandrehtrb/Pororoca#76]
Hi there!

Just found this project and I'm trying it out. Looks very cool, and not being Electron based is quite refreshing!!

I was testing [response Capture](https://pororoca.io/docs/response-capture) and missed the *Without an active environment in your collection, captures will not be made* warning so.. got stuck for a while there.

It would be nice if the app showed some warning in the "Capture" tab when there is no active environment, because no error is shown whatsoever in such case :(

**Comment by alexandrehtrb** [comment]
Yes, you are right, that is a little annoying

I will make a change to allow saving captured values into collection variables

**Comment by alexandrehtrb** [comment]
Solved in release 3.1.0

**Comment by telenieko** [comment]
> Solved in release 3.1.0

That was fast! :dancers:
