### ISSUE TITLE
Refactor PororocaWebSocketConnector to use Channel<T> instead of ObservableCollection<T> for exchanged messages

### ISSUE THREAD

**Issue by alexandrehtrb** [alexandrehtrb/Pororoca#78]
This would save memory and allow better threading

**Comment by umar-source** [comment]
I'd like to volunteer to refactor the PororocaWebSocketConnector to use Channel<T> instead of ObservableCollection<T> for exchanged messages, as described in issue.

**Comment by umardevX** [comment]
I'd like to volunteer to refactor the PororocaWebSocketConnector to use Channel instead of ObservableCollection for exchanged messages, as described in issue.
