### ISSUE TITLE
better response formatting for Websocket

### ISSUE THREAD

**Issue by marcob79** [alexandrehtrb/Pororoca#83]
Hi,
thank you so much for this wonderful tool.
I used since a couple of months for HTTP2 and recently I tried it also for websocket (I'm referring to version 3.1.0)
It would be possible to get a better (pretty) formatting of the response, especially in case of JSON ?

![image](https://github.com/alexandrehtrb/Pororoca/assets/66200214/5098d02f-a31f-46a8-a350-54b1a2fd191e)

**Comment by alexandrehtrb** [comment]
Yes, it can be done, it was supposed to be formatted :sweat_smile:
