### ISSUE TITLE
Feature request - plugins / encoding arbitrary file as base64

### ISSUE THREAD

**Issue by SoftExpert** [alexandrehtrb/Pororoca#89]
Hello,

While using Insomnia I was able to adapt a plugin that allowed me to load and use an arbitrary file as a Base64 encoded string inside the body of the request (as a value of a JSON attribute).

A screenshot of the original configuration:
![image](https://github.com/alexandrehtrb/Pororoca/assets/1254018/829760d7-cf9d-4b3a-a599-ffb1566b689a)

Here is a screenshot with the macro "loaded" with a file
![image](https://github.com/alexandrehtrb/Pororoca/assets/1254018/b6d74e62-0839-43cd-bffc-0db87d8c2e1b)

And here is a screenshot with its configuration interface in Insomnia
![image](https://github.com/alexandrehtrb/Pororoca/assets/1254018/dba5522c-c823-4ca8-b203-8f19281868ed)

It seems today there is no possibility to do that, so I'm wondering if there is a way to either implement it as a native feature or, at least, allow to add it through a plugin mechanism.

Thank you in advance for your help on this feature !

Best regards
SoftExpert

_Edited to add more screenshots_

**Comment by alexandrehtrb** [comment]
Sorry, @SoftExpert , but this use case is not common enough to be added as a feature, so I will close and mark this as not planned.

A plug-in system could exist, but is not planned in a near future.
