### ISSUE TITLE
Scrollbar not visible

### ISSUE THREAD

**Issue by john-brice** [alexandrehtrb/Pororoca#91]
The vertical scrollbar is not usually visible in Response pane. Headers and Body tabs.

If you shrink the pane by dragging the divider between Request/Response, it becomes visible (more is visible as the Response pane narrows).

Screen resolution/scaling do not seem to make a difference.

Windows 10 22H2 19045.4170
Pororoca 3.1.1

**Comment by alexandrehtrb** [comment]
Solved with release 3.2.0
